Repository RisingSunLight42/TD2_TRAVaie_IW, pull requests merged in 2023-10, with the labels that each got.

#40 Enhance security form
  js/app.js
Labels: js

#39 Mobile version
  css/style.css
Labels: css

#43 Add form option
  index.html
Labels: enhancement, html

#41 ✅ Add documentation
  js/app.js
Labels: documentation

#48 🌐 fix wrong language used
  index.html
  js/app.js
Labels: enhancement

#50 ✅ Add second part of form information
  index.html
  js/app.js
Labels: enhancement, js

#51 add style for form option
  css/style.css
  image/imgGithub.webp
  image/multivers.webp
  index.html
Labels: html, css

#52 Add images for better display
  image/a_bit_cloudy.webp
  image/cloudy.webp
  image/cloudy_sky.webp
  image/cloudy_sun.webp
  image/fog.webp
  image/more_cloudy.webp
  js/app.js
Labels: enhancement, js, html

#53 ✏️ Fix misspelling in first part
  js/app.js
Labels: bug

#54 🐛 fix page refresh when pressing enter on input field
  index.html
  js/app.js
Labels: bug, js, html

#56 Dynamic display
  index.html
  js/app.js
Labels: js

#58 Add display for all the new data
  README.md
  css/style.css
  image/firstIcons.txt
  image/icons/cloudy-day.svg
  image/icons/cloudy.svg
  image/icons/rainy.svg
  image/icons/snowy.svg
  image/icons/stormy.svg
  image/icons/sunny.svg
  index.html
  js/app.js
Labels: enhancement, js, html, css

#59 Add day selection
  css/style.css
  index.html
  js/app.js
Labels: enhancement, js, html, css

#60 Check norms
  css/style.css
  index.html
Labels: enhancement
